### ISSUE TITLE
Are react hooks on the roadmap ?

### ISSUE THREAD

**Issue by v9ai** [graphile/bootstrap-react-apollo#5]
Hello, I am interested in contributing to this project.
Based on react's team suggestion: https://reactjs.org/docs/hooks-faq.html#should-i-use-hooks-classes-or-a-mix-of-both - `In the longer term, we expect Hooks to be the primary way people write React components.` - I am also interested in investing time writing class-less React components.
What's your thoughts in this ?

**Comment by benjie** [comment]
Sure; I'd love to see the effects of changing to using hooks. Will they still work with SSR? I'm a little out of date when it comes to React right now!

**Comment by v9ai** [comment]
Based on this reponse: https://github.com/facebook/react/issues/13972#issuecomment-433255065
I think they will work with SSR, but I am not sure about other implications/ restrictions.
Even if there might be some edge cases when using hooks, I am pretty sure that these will get better soon.

**Comment by benjie** [comment]
How about Apollo; does their SSR support work with hooks?

**Comment by v9ai** [comment]
Great question, I am not 100% sure about this.
But I see that there are implementations like this: https://github.com/trojanowski/react-apollo-hooks

More importantly, as I heard in a discussion on a podcast (this is the episode if I remember correctly https://reactpodcast.simplecast.fm/37) - react will be back compatible even with `createElement` since there are a lot of component in Facebook written in an older way. So there might a mix with hooks and classes were hooks cannot solve the immediate problem.

**Comment by benjie** [comment]
I'm certainly willing to entertain hooks; but let's stick with the official way of doing things from the various vendors, and I think from Apollo that means sticking with their Query components/HOC for now. I've done SSR in another project with hooks without issues (but still using the old Apollo interfaces). If you're interested in modernising our React code I'm all for that - but let's not go too bleeding-edge!

**Comment by v9ai** [comment]
Ok, agree with - `the official way of doing things from the various vendors`.
